[2024-01-13T23:27:04.919+0500] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2024-01-13T18:16:39.944541+00:00 [queued]>
[2024-01-13T23:27:04.923+0500] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2024-01-13T18:16:39.944541+00:00 [queued]>
[2024-01-13T23:27:04.923+0500] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-01-13T23:27:04.932+0500] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): train_model> on 2024-01-13 18:16:39.944541+00:00
[2024-01-13T23:27:04.934+0500] {standard_task_runner.py:60} INFO - Started process 11543 to run task
[2024-01-13T23:27:04.937+0500] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'train_model', 'manual__2024-01-13T18:16:39.944541+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpcvke3nh1']
[2024-01-13T23:27:04.938+0500] {standard_task_runner.py:88} INFO - Job 26: Subtask train_model
[2024-01-13T23:27:04.961+0500] {task_command.py:423} INFO - Running <TaskInstance: youtube_comments_score.train_model manual__2024-01-13T18:16:39.944541+00:00 [running]> on host ubuntu
[2024-01-13T23:27:04.992+0500] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-01-13T18:16:39.944541+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-13T18:16:39.944541+00:00'
[2024-01-13T23:27:04.995+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-13T23:27:04.995+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/ml-srv/ml_pr3/scripts/train_model.py']
[2024-01-13T23:27:05.002+0500] {subprocess.py:86} INFO - Output:
[2024-01-13T23:27:05.606+0500] {subprocess.py:93} INFO - /home/ml-srv/ml_pr3/scripts/train_model.py:8: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
[2024-01-13T23:27:05.607+0500] {subprocess.py:93} INFO -   df.colums = ["idx", "counts"]
[2024-01-13T23:27:05.609+0500] {subprocess.py:93} INFO -    0     1
[2024-01-13T23:27:05.609+0500] {subprocess.py:93} INFO - 0  0   nan
[2024-01-13T23:27:05.610+0500] {subprocess.py:93} INFO - 1  1   nan
[2024-01-13T23:27:05.766+0500] {subprocess.py:97} INFO - Command exited with return code 255
[2024-01-13T23:27:05.771+0500] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ml-srv/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml-srv/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 255.
[2024-01-13T23:27:05.773+0500] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=youtube_comments_score, task_id=train_model, execution_date=20240113T181639, start_date=20240113T182704, end_date=20240113T182705
[2024-01-13T23:27:05.780+0500] {standard_task_runner.py:107} ERROR - Failed to execute job 26 for task train_model (Bash command failed. The command returned a non-zero exit code 255.; 11543)
[2024-01-13T23:27:05.803+0500] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-13T23:27:05.813+0500] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
