[2024-01-14T16:29:02.542+0500] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2024-01-14T11:29:00.694583+00:00 [queued]>
[2024-01-14T16:29:02.547+0500] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2024-01-14T11:29:00.694583+00:00 [queued]>
[2024-01-14T16:29:02.548+0500] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-14T16:29:02.563+0500] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): get_data> on 2024-01-14 11:29:00.694583+00:00
[2024-01-14T16:29:02.566+0500] {standard_task_runner.py:60} INFO - Started process 8103 to run task
[2024-01-14T16:29:02.568+0500] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'manual__2024-01-14T11:29:00.694583+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmp959s705o']
[2024-01-14T16:29:02.570+0500] {standard_task_runner.py:88} INFO - Job 34: Subtask get_data
[2024-01-14T16:29:02.597+0500] {task_command.py:423} INFO - Running <TaskInstance: youtube_comments_score.get_data manual__2024-01-14T11:29:00.694583+00:00 [running]> on host ubuntu
[2024-01-14T16:29:02.637+0500] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-14T11:29:00.694583+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-14T11:29:00.694583+00:00'
[2024-01-14T16:29:02.638+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-14T16:29:02.638+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/ml-srv/ml_pr3/scripts/get_data.py']
[2024-01-14T16:29:02.644+0500] {subprocess.py:86} INFO - Output:
[2024-01-14T16:29:36.283+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-01-14T16:29:36.283+0500] {subprocess.py:93} INFO -   File "/home/ml-srv/ml_pr3/scripts/get_data.py", line 39, in <module>
[2024-01-14T16:29:36.283+0500] {subprocess.py:93} INFO -     for item in data["items"]:
[2024-01-14T16:29:36.283+0500] {subprocess.py:93} INFO -                 ~~~~^^^^^^^^^
[2024-01-14T16:29:36.284+0500] {subprocess.py:93} INFO - KeyError: 'items'
[2024-01-14T16:29:36.348+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-14T16:29:36.353+0500] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ml-srv/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml-srv/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-14T16:29:36.356+0500] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=get_data, execution_date=20240114T112900, start_date=20240114T112902, end_date=20240114T112936
[2024-01-14T16:29:36.366+0500] {standard_task_runner.py:107} ERROR - Failed to execute job 34 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 8103)
[2024-01-14T16:29:36.391+0500] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-14T16:29:36.405+0500] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
