[2024-01-14T17:14:49.835+0500] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.test_model manual__2024-01-14T12:13:48.350409+00:00 [queued]>
[2024-01-14T17:14:49.840+0500] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.test_model manual__2024-01-14T12:13:48.350409+00:00 [queued]>
[2024-01-14T17:14:49.841+0500] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-14T17:14:49.849+0500] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): test_model> on 2024-01-14 12:13:48.350409+00:00
[2024-01-14T17:14:49.852+0500] {standard_task_runner.py:60} INFO - Started process 16072 to run task
[2024-01-14T17:14:49.856+0500] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'test_model', 'manual__2024-01-14T12:13:48.350409+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpt4flm6zt']
[2024-01-14T17:14:49.857+0500] {standard_task_runner.py:88} INFO - Job 54: Subtask test_model
[2024-01-14T17:14:49.880+0500] {task_command.py:423} INFO - Running <TaskInstance: youtube_comments_score.test_model manual__2024-01-14T12:13:48.350409+00:00 [running]> on host ubuntu
[2024-01-14T17:14:49.922+0500] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='test_model' AIRFLOW_CTX_EXECUTION_DATE='2024-01-14T12:13:48.350409+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-14T12:13:48.350409+00:00'
[2024-01-14T17:14:49.923+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-14T17:14:49.923+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/ml-srv/ml_pr3/scripts/test_model.py']
[2024-01-14T17:14:49.930+0500] {subprocess.py:86} INFO - Output:
[2024-01-14T17:14:50.679+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-01-14T17:14:50.679+0500] {subprocess.py:93} INFO -   File "/home/ml-srv/ml_pr3/scripts/test_model.py", line 12, in <module>
[2024-01-14T17:14:50.679+0500] {subprocess.py:93} INFO -     df["counts"] = df["counts"].replace(to_replace=[np.nan], value=0, inplace=True)
[2024-01-14T17:14:50.679+0500] {subprocess.py:93} INFO -                                                     ^^
[2024-01-14T17:14:50.679+0500] {subprocess.py:93} INFO - NameError: name 'np' is not defined
[2024-01-14T17:14:50.853+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-14T17:14:50.857+0500] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ml-srv/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml-srv/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-14T17:14:50.861+0500] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=test_model, execution_date=20240114T121348, start_date=20240114T121449, end_date=20240114T121450
[2024-01-14T17:14:50.870+0500] {standard_task_runner.py:107} ERROR - Failed to execute job 54 for task test_model (Bash command failed. The command returned a non-zero exit code 1.; 16072)
[2024-01-14T17:14:50.879+0500] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-14T17:14:50.886+0500] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
