[2024-01-13T23:19:17.603+0500] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2024-01-13T18:19:04.599628+00:00 [queued]>
[2024-01-13T23:19:17.609+0500] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2024-01-13T18:19:04.599628+00:00 [queued]>
[2024-01-13T23:19:17.609+0500] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-13T23:19:17.618+0500] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): train_model> on 2024-01-13 18:19:04.599628+00:00
[2024-01-13T23:19:17.620+0500] {standard_task_runner.py:60} INFO - Started process 8455 to run task
[2024-01-13T23:19:17.623+0500] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'train_model', 'manual__2024-01-13T18:19:04.599628+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpmhwj3jjp']
[2024-01-13T23:19:17.624+0500] {standard_task_runner.py:88} INFO - Job 16: Subtask train_model
[2024-01-13T23:19:17.647+0500] {task_command.py:423} INFO - Running <TaskInstance: youtube_comments_score.train_model manual__2024-01-13T18:19:04.599628+00:00 [running]> on host ubuntu
[2024-01-13T23:19:17.682+0500] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-01-13T18:19:04.599628+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-13T18:19:04.599628+00:00'
[2024-01-13T23:19:17.683+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-13T23:19:17.683+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/ml-srv/ml_pr3/scripts/train_model.py']
[2024-01-13T23:19:17.689+0500] {subprocess.py:86} INFO - Output:
[2024-01-13T23:19:18.901+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-01-13T23:19:18.902+0500] {subprocess.py:93} INFO -   File "/home/ml-srv/ml_pr3/scripts/train_model.py", line 7, in <module>
[2024-01-13T23:19:18.902+0500] {subprocess.py:93} INFO -     df = pd.read_csv("/home/ml-srv/mp_pr3/datasets/data_train.csv", header=None)
[2024-01-13T23:19:18.902+0500] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-01-13T23:19:18.902+0500] {subprocess.py:93} INFO -   File "/home/ml-srv/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
[2024-01-13T23:19:18.902+0500] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2024-01-13T23:19:18.903+0500] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-01-13T23:19:18.903+0500] {subprocess.py:93} INFO -   File "/home/ml-srv/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 611, in _read
[2024-01-13T23:19:18.903+0500] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2024-01-13T23:19:18.903+0500] {subprocess.py:93} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-01-13T23:19:18.903+0500] {subprocess.py:93} INFO -   File "/home/ml-srv/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
[2024-01-13T23:19:18.903+0500] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2024-01-13T23:19:18.903+0500] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-01-13T23:19:18.903+0500] {subprocess.py:93} INFO -   File "/home/ml-srv/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
[2024-01-13T23:19:18.903+0500] {subprocess.py:93} INFO -     self.handles = get_handle(
[2024-01-13T23:19:18.903+0500] {subprocess.py:93} INFO -                    ^^^^^^^^^^^
[2024-01-13T23:19:18.903+0500] {subprocess.py:93} INFO -   File "/home/ml-srv/.local/lib/python3.11/site-packages/pandas/io/common.py", line 863, in get_handle
[2024-01-13T23:19:18.904+0500] {subprocess.py:93} INFO -     handle = open(
[2024-01-13T23:19:18.904+0500] {subprocess.py:93} INFO -              ^^^^^
[2024-01-13T23:19:18.904+0500] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/home/ml-srv/mp_pr3/datasets/data_train.csv'
[2024-01-13T23:19:19.066+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-13T23:19:19.071+0500] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ml-srv/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml-srv/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-13T23:19:19.075+0500] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=train_model, execution_date=20240113T181904, start_date=20240113T181917, end_date=20240113T181919
[2024-01-13T23:19:19.083+0500] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task train_model (Bash command failed. The command returned a non-zero exit code 1.; 8455)
[2024-01-13T23:19:19.109+0500] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-13T23:19:19.119+0500] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
