[2024-01-13T23:11:48.925+0500] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2024-01-13T18:05:51.887756+00:00 [queued]>
[2024-01-13T23:11:48.929+0500] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2024-01-13T18:05:51.887756+00:00 [queued]>
[2024-01-13T23:11:48.929+0500] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-01-13T23:11:48.940+0500] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): get_data> on 2024-01-13 18:05:51.887756+00:00
[2024-01-13T23:11:48.942+0500] {standard_task_runner.py:60} INFO - Started process 6235 to run task
[2024-01-13T23:11:48.945+0500] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'manual__2024-01-13T18:05:51.887756+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpx2ohptt5']
[2024-01-13T23:11:48.946+0500] {standard_task_runner.py:88} INFO - Job 7: Subtask get_data
[2024-01-13T23:11:48.969+0500] {task_command.py:423} INFO - Running <TaskInstance: youtube_comments_score.get_data manual__2024-01-13T18:05:51.887756+00:00 [running]> on host ubuntu
[2024-01-13T23:11:49.001+0500] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-13T18:05:51.887756+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-13T18:05:51.887756+00:00'
[2024-01-13T23:11:49.002+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-13T23:11:49.002+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/ml-srv/ml_pr3/scripts/get_data.py']
[2024-01-13T23:11:49.007+0500] {subprocess.py:86} INFO - Output:
[2024-01-13T23:11:49.105+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-01-13T23:11:49.105+0500] {subprocess.py:93} INFO -   File "/home/ml-srv/ml_pr3/scripts/get_data.py", line 13, in <module>
[2024-01-13T23:11:49.105+0500] {subprocess.py:93} INFO -     from pyyoutube import Api
[2024-01-13T23:11:49.105+0500] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'pyyoutube'
[2024-01-13T23:11:49.128+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-13T23:11:49.133+0500] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ml-srv/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml-srv/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-13T23:11:49.136+0500] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=youtube_comments_score, task_id=get_data, execution_date=20240113T180551, start_date=20240113T181148, end_date=20240113T181149
[2024-01-13T23:11:49.142+0500] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 6235)
[2024-01-13T23:11:49.163+0500] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-13T23:11:49.174+0500] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
